export type FormStep=1|2|3|4
export type FormValues = {
    brand: string,
    state: string,
    country: string,
    deviceType: string,
    deviceNo: string,
    deviceName:string,
    firstName: string,
    lastName: string,
    gender: string,
    nationality: string,
    address: string,
    mobileNo: string,
    idCard: string,
    idNumber: string,
    contactPersonName:string,
    ContactPersonRelation: string,
    ContactPersonAddress: string,
    ContactPersonMobileNo: string,
    reciverName: string,
    reciverAddress: string,
    dateOfDelivery: string,
    message: string,
    reciverMobileNo: string,
    agree: string,
  };